import { startServer } from "./server/startServer";
import type { CF5KIT_APP } from "./types/APP";

/**
 * DO NOT EDIT THIS FILE
 * EDIT ./src/app.ts
 */

export class CF5KIT {
	app: CF5KIT_APP;

	constructor(APP: CF5KIT_APP) {
		this.app = APP;
	}

	dev() {
		startServer(this.app);
	}
}
